### ISSUE TITLE
run lipo bug

### ISSUE THREAD

**Issue by TurkeyTeo** [HikariObfuscator/Noctilucence#1]
MachOObjectFile &MachO = *BinaryOrErr.get();
 string ret = HandleMachOObjFile(&MachO, argv);
line 370, get the Mach-O file name needs to be copied, otherwise the Data in lipoargs may changed. 
I recently upgraded the Hikari version to LLVM_90, added Obfusion file and also put MPM.add(createObfuscationPass()) in PassManagerBuilder::populateModulePassManager. The result is Flattening and FunctionWrapper get an error, Any suggestions on how to do it，tks

**Comment by Naville** [comment]
英文没看懂，我看得懂中文。
另外9.0需要hikari core本身移植才能支持，你单纯复制文件还是会出问题的

**Comment by Naville** [comment]
> line 370, get the Mach-O file name needs to be copied, otherwise the Data in lipoargs may changed.

你是说这个有bug是吧，给我开个PR修一下吧
