### ISSUE TITLE
Hey Can You help me with something about Utils Library?

### ISSUE THREAD

**Issue by EchoSkill** [HikariObfuscator/Noctilucence#3]
Can you please tech me how I can fix this issue about Utils Library? 
I have this error when try compile Noctilucence 
![image](https://user-images.githubusercontent.com/8241890/113191367-104e2700-9223-11eb-9fe1-6385e515f62c.png)

**Comment by Naville** [comment]
https://github.com/HikariObfuscator/Noctilucence/blob/master/LLVMBuild.txt

Try remove Utils from here

**Comment by EchoSkill** [comment]
I have already deleted and it has started to compile normally but now before finishing the compilation it gives me an error when finishing compiling,
![image](https://user-images.githubusercontent.com/8241890/113309213-878bc580-92cc-11eb-9a28-23e4d101d078.jpeg)
And I begin to believe that it is because of that library because previously without adding Noctilucence it compiled correctly, but now I wanted to add support for arm64e and I have this problem, what do you think it could be?

Thanks for answering

**Comment by Naville** [comment]
Look at the full crash log, there are usually some more detailed crash log somewhere above

**Comment by EchoSkill** [comment]
I think I found what you mean, it seems to be an architecture problem, could you guide me to what you mean? Or how to proceed please?
As I told you, before adding Noctilucence, the Toolchain compiled fine.

![image](https://user-images.githubusercontent.com/8241890/113311285-c458bc00-92ce-11eb-84e7-921242e4ecf6.jpeg)
![image](https://user-images.githubusercontent.com/8241890/113311305-c753ac80-92ce-11eb-83e1-8d780d32aa6f.jpeg)

**Comment by Naville** [comment]
It tried to link with libxar and failed

**Comment by EchoSkill** [comment]
Oh, I understand you, thank you very much.
Does this .dylib have to be downloaded from a special source?
Because I have downloaded it from another GitHub source since it was not found on my Mac by default.

**Comment by Naville** [comment]
It was shipped with macOS at the time I wrote this project

**Comment by EchoSkill** [comment]
After so many attempts I have managed to compile it with the OSX 10.10 version of libxar.dylib,
But now when I run: Noctilucence -i < path my dylib> -o < new path> -enable-strcry

It returns the following as an error,
![image](https://user-images.githubusercontent.com/8241890/113330468-6040f280-92e4-11eb-90d0-5de021e64e39.jpeg) 

Any ideas ?
Sorry for the inconvenience and thanks again for answering

**Comment by Naville** [comment]
It literally said bitcode not found at the top

**Comment by EchoSkill** [comment]
sorry for disturb,,, but, how I can fix this?

**Comment by Naville** [comment]
If you don't know what BitCode is and won't / can't use Google to find it out then this project is probably not for you.
